# Generated by Django 5.1.1 on 2024-10-13 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0008_rename_code_category_id_rename_code_subcategory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isAnswered', models.BooleanField()),
                ('isAnsweredCorrect', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestionChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isSelected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('questionNumber', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('random', models.BooleanField(default=False)),
                ('correctNumber', models.PositiveIntegerField(default=0)),
                ('lastAnsweredQuestionIndex', models.PositiveIntegerField(default=0)),
                ('wrongNumber', models.PositiveIntegerField(default=0)),
                ('time', models.PositiveIntegerField(default=0)),
                ('default_quiz', models.BooleanField(default=False)),
                ('subcategories', models.ManyToManyField(to='question.subcategory')),
            ],
        ),
    ]
