# Generated by Django 5.1.1 on 2024-10-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='code',
            field=models.CharField(db_index=True, default='DyRGTaMlqSRfMr7bQVOH', editable=False, max_length=20, unique=True),
        ),
    ]
