# Generated by Django 5.1.1 on 2024-10-13 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_grade_available_wilaya_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='question.grade'),
        ),
        migrations.AddField(
            model_name='question',
            name='wilaya',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.wilaya'),
        ),
    ]
