# Generated by Django 5.1.1 on 2024-10-13 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_question_grade_question_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.grade'),
        ),
    ]
