# Generated by Django 5.1.1 on 2024-10-13 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_alter_category_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='wilaya',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.wilaya'),
        ),
    ]
