# Generated by Django 5.1.1 on 2024-10-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_category_wilaya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='code',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='code',
            new_name='id',
        ),
    ]
